In [ ]:
'''
🚀 Projeto 7/15 — Análise de dados com SQL + Python
Objetivo

Aprender a integrar Python + SQL, algo muito comum em pipelines reais.

Você vai:

Dataset → SQLite → consultas SQL → análise → visualização
📊 Cenário do projeto

Analisar vendas de uma loja online.

Perguntas que queremos responder:

1️⃣ Qual produto vende mais?
2️⃣ Qual categoria gera mais receita?
3️⃣ Qual mês teve maior faturamento?
4️⃣ Qual ticket médio por pedido?

📁 Dataset

Pode usar um dataset simples de e-commerce.

Sugestão:

Superstore dataset (muito usado em analytics).

Se quiser algo menor, podemos simular também.

Exemplo de colunas:

order_id
order_date
product
category
quantity
price
region
🧠 Skills que você vai treinar
SQL (SELECT, GROUP BY, ORDER BY)
Python
Pandas
SQLite
Análise de métricas
Visualização

🏗️ Pipeline do projeto

Para manter o padrão dos seus posts:

Dataset CSV
↓
Load para SQLite
↓
Consultas SQL
↓
DataFrame Pandas
↓
Análise de métricas
↓
Visualização
🧩 Etapa 1 — Criar banco SQLite

import sqlite3

🧩 Etapa 2 — Consulta SQL

Exemplo: produtos mais vendidos

query = """
SELECT product,
       SUM(quantity) as total_vendas
FROM sales
GROUP BY product
ORDER BY total_vendas DESC
LIMIT 10
"""

top_products = pd.read_sql(query, conn)
🧩 Etapa 3 — Visualização..

In [2]:
!pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\hyego jarllys\appdata\local\programs\python\python313\lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in c:\users\hyego jarllys\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in c:\users\hyego jarllys\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\users\hyego jarllys\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\users\hyego jarllys\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (2.31.0)
Requirement already satisfied: tqdm in c:\users\hyego jarllys\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\hyego jarllys\appdata\local\programs\python\python313\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (4.25.8)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hyego jarllys\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hyego jarllys\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hyego jarllys\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hyego jarllys\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (2025.11.12)
Requirement already satisfied: colorama in c:\users\hyego jarllys\appdata\local\programs\python\python313\lib\site-packages (from tqdm->kagglehub) (0.4.6)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# INGESTÂO
import pandas as pd
import matplotlib.pyplot as plt
import kagglehub

# Download dataset
path = kagglehub.dataset_download("vivek468/superstore-dataset-final")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Hyego Jarllys\.cache\kagglehub\datasets\vivek468\superstore-dataset-final\versions\1

In [4]:
import os

# 1. O caminho do arquivo
path = r"C:\Users\Hyego Jarllys\.cache\kagglehub\datasets\vivek468\superstore-dataset-final\versions\1"

# 2. Vamos listar os arquivos e ver o nome exato do CSV
arquivo = os.listdir(path)
print("Arquivos encontrados:", arquivo)

Arquivos encontrados: ['Sample - Superstore.csv']

In [5]:
#criação do Data Frame
caminho_origem=r"C:\Users\Hyego Jarllys\.cache\kagglehub\datasets\vivek468\superstore-dataset-final\versions\1\Sample - Superstore.csv"
df = pd.read_csv(caminho_origem, encoding='windows-1252')

In [ ]:
#TRANSFORMAÇÂO
df.shape
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df=df.drop_duplicates()
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

In [15]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 3.2 MB

In [19]:
#Gravar no DataBase

import sqlite3

conn = sqlite3.connect("Superstore.db")

df.to_sql("Superstore", conn, if_exists="replace", index=False)
df.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136

In [25]:
#Queryes
query=  """
select "Product Name", Quantity as 'Quantidade'
from Superstore
order by Quantity desc
limit 1
"""
mais_vendido=pd.read_sql(query,conn)
print(mais_vendido)

                               Product Name  Quantidade
0  OIC Colored Binder Clips, Assorted Sizes          14

In [28]:
query="""
select Category, round(sum(Profit),2) as ' Receita'
from Superstore
group by Category
order by sum(Profit) desc
"""
maior_categoria=pd.read_sql(query,conn)
print(maior_categoria)

          Category    Receita
0       Technology  145454.95
1  Office Supplies  122490.80
2        Furniture   18451.27

In [32]:
query = """
SELECT strftime('%m/%Y', [Order Date]) as Mes_Ano,
       ROUND(SUM(Sales), 2) as Faturamento
FROM Superstore
GROUP BY Mes_Ano
ORDER BY Faturamento DESC
LIMIT 10
"""

df_mensal = pd.read_sql(query, conn)
print(df_mensal)

   Mes_Ano  Faturamento
0  11/2017    118447.82
1  12/2016     96999.04
2  09/2017     87866.65
3  12/2017     83829.32
4  09/2014     81777.35
5  11/2016     79411.97
6  11/2014     78628.72
7  10/2017     77776.92
8  11/2015     75972.56
9  12/2015     74919.52

In [ ]:
'''
1️⃣ Qual produto vende mais?
2️⃣ Qual categoria gera mais receita?
3️⃣ Qual mês teve maior faturamento?
4️⃣ Qual ticket médio por pedido?
# 1. A Pergunta (Query)
# Escrevemos em SQL puro dentro de uma variável de texto (string)
query = """
SELECT Category, SUM(Sales) as Total_Vendas
FROM sales
GROUP BY Category
ORDER BY Total_Vendas DESC
"""

# 2. O Mensageiro (Pandas + Connection)
# O pd.read_sql pega a query e a conexão 'conn' para buscar o dado
df_resultado = pd.read_sql(query, conn)

# 3. A Resposta
# O resultado volta para você já formatado como um novo DataFrame do Pandas
print(df_resultado)
'''